config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :profiles, only: [:show], param: :nickname
  resources :task_lists, only: [:index, :create, :show] do
    resources :tasks, only: [:create, :update, :destroy]
    resources :chatrooms do
      resources :messages, only: :create
    end
    resources :invitations, only: [:create] do
      member do
        get 'accept/:token', action: 'accept', as: 'accept'
        get 'decline/:token', action: 'decline', as: 'decline'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :task_list
end

app/models/chatroom_profile.rb
class ChatroomProfile < ApplicationRecord
  belongs_to :chatroom
  belongs_to :profile
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :inviter, class_name: 'Profile'
  belongs_to :invitee, class_name: 'Profile'
  belongs_to :task_list
  after_create :generate_token

  def generate_token
    self.token = SecureRandom.hex(10)
    self.save
  end
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :profiles
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :profile
  belongs_to :chatroom
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :level
  has_many :profile_task_lists
  has_many :task_lists, through: :profile_task_lists
  has_many :invitations_sent, foreign_key: 'inviter_id', class_name: 'Invitation'
  has_many :invitations_received, foreign_key: 'invitee_id', class_name: 'Invitation'
  has_many :messages
  validates :nickname, presence: true, uniqueness: true
  before_validation :add_level, on: :create

  def add_level
    self.level ||= Level.find_by(name: "one")
  end

end

app/models/profile_task_list.rb
class ProfileTaskList < ApplicationRecord
  belongs_to :profile
  belongs_to :task_list
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list
  belongs_to :task_category
end

app/models/task_category.rb
class TaskCategory < ApplicationRecord
  has_many :tasks
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  belongs_to :profile
  has_one :chatroom, dependent: :destroy
  has_many :profile_task_lists, dependent: :destroy
  has_many :profiles, through: :profile_task_lists
  has_many :tasks, dependent: :destroy
  has_many :invitations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.profile = current_user.profile
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
      # hello
    else
      render "task_list/show/#{params[:task_list_id]}"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
    @task_list = current_user.profile.task_lists.build
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find_by(nickname: params[:nickname])
    @received_invitations = @profile.invitations_received
    @sent_invitations = @profile.invitations_sent
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController

  def index
    @profile = current_user.profile
    @task_list = @profile.task_lists.build
    @task_lists = @profile.task_lists
  end

  def show
    @task_list = TaskList.find(params[:id])
    @chatroom = Chatroom.find_by(task_list: @task_list) || Chatroom.create(task_list: @task_list)
    @message = Message.new
    @task = Task.new
    @invitation = Invitation.new
    @profiles = Profile.all.where.not(id: current_user.profile.id)
  end

  def create
    # @task_list = current_user.profile.task_lists.build(task_list_params)
    @task_list = TaskList.new(task_list_params)
    @task_list.profiles << current_user.profile
    @task_list.profile = current_user.profile
    if @task_list.save!
      redirect_to task_list_path(@task_list)
    else
      render :new
    end
  end

  def destroy; end

  private

  def task_list_params
    params.require(:task_list).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @task_list = TaskList.find(params[:task_list_id])
    @task = @task_list.tasks.build(task_params)
    if @task.save
      TaskListChannel.broadcast_to(
        @task_list,
        render_to_string(partial: "task", locals: { task: @task })
      )
      # respond_to do |format|
      #   format.html { redirect_to task_list_path(@task_list) }
      #   format.js { render 'create', locals: { task: @task } }
      # end
    else
      respond_to do |format|
        format.html { render :new }
        format.js { render 'fail_create', locals: { task: @task } }
      end
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :task_category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.profile.nickname %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/profiles/show.html.erb
<h1>Profile</h1>
<%= @profile.nickname %>
<h2>You have received these invites:</h2>
<% @received_invitations.each do |received| %>
  <p>Task List name: <%= received.task_list.name %></p>
  <p>You are invited by: <%= received.inviter.nickname %></p>
  <%= link_to "Accept", accept_task_list_invitation_path(received.task_list, received, received.token) %>
  <%= link_to "Decline", decline_task_list_invitation_path(received.task_list, received, received.token) %>
<% end %>
<h2>You have sent these invites:</h2>
<% @sent_invitations.each do |sent| %>
  <p>Task List name: <%= sent.task_list.name %></p>
  <p>You invited: <%= sent.invitee.nickname %></p>
<% end %>

app/views/task_lists/_form.html.erb
<%= simple_form_for @task_list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/task_lists/_task_list.html.erb
<%= task_list.name %>
<%= task_list.tasks.each do |task| %>
  <%= task.name %>
  <%= task.description %>
<% end %>

app/views/task_lists/index.html.erb
<h1>Task Lists</h1>
<%= render 'form' %>

<h2>My Lists</h2>
<% @task_lists.each do |list| %>
  <% unless list.id == nil %>
    <%= link_to "Show", task_list_path(list) %>
    <%= render 'task_list', task_list: list %>
  <% end %>
<% end %>

app/views/task_lists/show.html.erb
<h1>Task List</h1>
<% @task_list.profiles.each do |profile| %>
  <p><%= profile.nickname %></p>
<% end %>
<div id="tasks">
  <%= render 'tasks/form', task: @task %>
  <div class="container tasklist"
  data-controller="task-list-subscription"
  data-task-list-subscription-task-list-id-value="<%= @task_list.id %>">
    <div data-task-list-subscription-target="tasks">
    <% @task_list.tasks.each do |task| %>
      <%= render 'tasks/task', task: task %>
    <% end %>
    </div>
  </div>
</div>

<%= render 'invitations/form',  invitation: @invitation %>

<%= simple_form_for [@task_list, @chatroom, @message],
  html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, remote: true, class: "d-flex" } do |f|
%>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
>
  <h1>#<%= @chatroom.id %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">

    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>

</div>

app/views/tasks/_form.html.erb
<h1>ADD NEW TASK</h1>
  <%= simple_form_for [@task_list, @task], remote: true, id: 'new_task' do |f| %>
    <%= f.input :task_category_id, collection: TaskCategory.all %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit %>
  <% end %>

app/views/tasks/_task.html.erb
<div class="task">
  <%= task.name %>
  <%= task.description %>
</div>

app/views/tasks/create.js.erb
<%# document.getElementById('tasks').insertAdjacentHTML('beforeend', '<%= j render "tasks/task", task: @task %>
document.getElementById('new_task').reset();

app/views/tasks/fail_create.js.erb
alert("Didnt work to create task")